import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";

export default function AdminInvoicesTab() {
  const { data: invoices = [] } = useQuery<any[]>({
    queryKey: ["/api/admin/invoices"],
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case "sent":
        return "bg-blue-100 text-blue-800 hover:bg-blue-100";
      case "paid":
        return "bg-green-100 text-green-800 hover:bg-green-100";
      case "generated":
        return "bg-yellow-100 text-yellow-800 hover:bg-yellow-100";
      default:
        return "bg-gray-100 text-gray-800 hover:bg-gray-100";
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Invoice History</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Invoice Number</TableHead>
                <TableHead>Member</TableHead>
                <TableHead>Company</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {invoices.length > 0 ? (
                invoices.map((invoice: any) => (
                  <TableRow key={invoice.id}>
                    <TableCell className="font-medium">{invoice.invoiceNumber}</TableCell>
                    <TableCell>
                      <div>
                        <div className="font-medium">{invoice.memberName}</div>
                        <div className="text-sm text-gray-500">{invoice.memberEmail}</div>
                      </div>
                    </TableCell>
                    <TableCell>
                      {invoice.companyName ? (
                        <div>
                          <div>{invoice.companyName}</div>
                          {invoice.companyEmail && (
                            <div className="text-sm text-gray-500">{invoice.companyEmail}</div>
                          )}
                        </div>
                      ) : (
                        <span className="text-gray-400">N/A</span>
                      )}
                    </TableCell>
                    <TableCell>${parseFloat(invoice.amount).toFixed(2)} BSD</TableCell>
                    <TableCell>
                      <Badge className={getStatusColor(invoice.status)}>
                        {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {invoice.isAdminGenerated ? (
                        <Badge variant="default">Admin</Badge>
                      ) : (
                        <Badge variant="secondary">Member</Badge>
                      )}
                    </TableCell>
                    <TableCell>
                      {format(new Date(invoice.createdAt), 'MMM d, yyyy')}
                    </TableCell>
                    <TableCell>
                      {invoice.pdfPath && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={async () => {
                            try {
                              // Try to get download URL from API
                              const response = await fetch(`/api/objects/download?path=${encodeURIComponent(invoice.pdfPath)}`);
                              if (response.ok) {
                                const { downloadURL } = await response.json();
                                window.open(downloadURL, '_blank');
                              } else {
                                // Fallback: try to construct URL or use objectPath directly
                                window.open(invoice.pdfPath, '_blank');
                              }
                            } catch (error) {
                              // Fallback: try to open the path directly
                              window.open(invoice.pdfPath, '_blank');
                            }
                          }}
                        >
                          <i className="fas fa-download mr-2"></i>
                          View PDF
                        </Button>
                      )}
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={8} className="text-center py-8">
                    <div className="flex flex-col items-center">
                      <i className="fas fa-file-invoice text-gray-400 text-4xl mb-4"></i>
                      <h3 className="text-lg font-medium text-gray-900 mb-2">No Invoices</h3>
                      <p className="text-gray-500">No invoices have been generated yet.</p>
                    </div>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}
